# These substitutions allow the end user to override certain values
substitutions:
  name: "tagreader-st25r"
  friendly_name: "TagReader (ST25R)"

packages:
  # Include all of the core configuration
  core: !include non-iron-tagreader-atom-lite-st25r.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  project:
    name: LukaGra.${friendly_name}
    version: dev

ota:
  - platform: http_request
    id: ota_http_request

http_request:

update:
  - platform: http_request
    name: None
    id: update_http_request
    source: https://github.com/modem7/non-iron-tagreader-st25r/releases/latest/download/non-iron-tagreader-st25r-firmware.manifest.json

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://modem7/non-iron-tagreader-st25r/non-iron-tagreader-st25r.factory.yaml@main
  import_full_config: false

# Sets up the improv via serial client for Wi-Fi provisioning
# improv_serial:
#   next_url: https://github.com/luka6000/Non-Iron-TagReader

esp32_ble:
  name: TagReaderST25
esp32_improv:
  authorizer: toggle
